#ifndef _MCAL_ATMEGA32REGISTER_H
#define _MCAL_ATMEGA32REGISTER_H
#include <stdint.h>

#define SREG_R *((volatile uint8_t*)0x5F)
#define SPH_R *((volatile uint8_t*)0x5E)
#define SPL_R *((volatile uint8_t*)0x5D)
#define SP_R  *((volatile uint16_t*)0x5D)
#define OCRO_R *((volatile uint8_t *)0x5C)
#define GICR_R *((volatile uint8_t *)0x5B)
#define GIFR_R *((volatile uint8_t *)0x5A)
#define TIMSK_R *((volatile uint8_t *)0x59)
#define TIFR_R *((volatile uint8_t *)0x58)
#define SPMCR_R *((volatile uint8_t *)0x57)
#define TWCR_R *((volatile uint8_t *)0x56)
#define MCUCR_R *((volatile uint8_t *)0x55)
#define MCUCSR_R *((volatile uint8_t *)0x54)
#define TCCRO_R *((volatile uint8_t *)0x53)
#define TCNTO_R *((volatile uint8_t *)0x52)
#define OSCCAL_R *((volatile uint8_t *)0x52)
#define OCDR_R *((volatile uint8_t *)0x51)
#define SFIOR_R *((volatile uint8_t *)0x50)
#define TCCR1A_R *((volatile uint8_t *)0x4F)
#define TCCR1B_R *((volatile uint8_t *)0x4E)
#define TCNT1H_R *((volatile uint8_t *)0x4D)
#define TCNT1L_R *((volatile uint8_t *)0x4C)
#define OCR1AH_R *((volatile uint8_t *)0x4B)
#define OCR1AL_R *((volatile uint8_t *)0x4A)
#define OCR1BH_R *((volatile uint8_t *)0x49)
#define OCR1BL_R *((volatile uint8_t *)0x48)
#define ICR1H_R *((volatile uint8_t *)0x47)
#define ICR1L_R *((volatile uint8_t *)0x46)
#define TCCR2_R *((volatile uint8_t *)0x45)
#define TCNT2_R *((volatile uint8_t *)0x44)
#define OCR2_R *((volatile uint8_t *)0x43)
#define ASSR_R *((volatile uint8_t *)0x42)
#define WDTCR_R *((volatile uint8_t *)0x41)
#define UBRRH_R *((volatile uint8_t *)0x41)
#define UCSRC_R *((volatile uint8_t *)0x40)
#define EEARH_R *((volatile uint8_t *)0x3F)
#define EEARL_R *((volatile uint8_t *)0x3E)
#define EEDR_R *((volatile uint8_t *)0x3D)
#define EECR_R *((volatile uint8_t *)0x3C)
#define PORTA_R *((volatile uint8_t *)0x3B)
#define DDRA_R *((volatile uint8_t *)0x3A)
#define PINA_R *((volatile uint8_t *)0x39)
#define PORTB_R *((volatile uint8_t *)0x38)
#define DDRB_R *((volatile uint8_t *)0x37)
#define PINB_R *((volatile uint8_t *)0x36)
#define PORTC_R *((volatile uint8_t *)0x35)
#define DDRC_R *((volatile uint8_t *)0x34)
#define PINC_R *((volatile uint8_t *)0x33)
#define PORTD_R *((volatile uint8_t *)0x32)
#define DDRD_R *((volatile uint8_t *)0x31)
#define PIND_R *((volatile uint8_t *)0x30)
#define SPDR_R *((volatile uint8_t *)0x2F)
#define SPSR_R *((volatile uint8_t *)0x2E)
#define SPCR_R *((volatile uint8_t *)0x2D)
#define UDR_R *((volatile uint8_t *)0x2C)
#define UCSRA_R *((volatile uint8_t *)0x2B)
#define UCSRB_R *((volatile uint8_t *)0x2A)
#define UBRRL_R *((volatile uint8_t *)0x29)
#define ACSR_R *((volatile uint8_t *)0x28)
#define ADMUX_R *((volatile uint8_t *)0x27)
#define ADCSRA_R *((volatile uint8_t *)0x26)
#define ADCH_R *((volatile uint8_t *)0x25)
#define ADCL_R *((volatile uint8_t *)0x24)
#define TWDR_R *((volatile uint8_t *)0x23)
#define TWAR_R *((volatile uint8_t *)0x22)
#define TWSR_R *((volatile uint8_t *)0x21)
#define TWBR_R *((volatile uint8_t *)0x20)

#endif
